blueprint:
  name: Siren ESPHome – Phát âm thanh có thời lượng
  description: >
    Kích hoạt còi ESPHome Siren với lựa chọn âm thanh,
    âm lượng và thời lượng.
  domain: automation

  input:
    trigger_event:
      name: Điều kiện kích hoạt
      selector:
        trigger:

    siren_switch:
      name: Công tắc kích hoạt còi
      description: Kích hoạt
      selector:
        entity:
          domain: switch

    duration_number:
      name: "Thực thể: Thời lượng"
      description: number.alarm_duration (đơn vị giây)
      selector:
        entity:
          domain: number

    sound_entity:
      name: "Thực thể: Âm thanh"
      selector:
        entity:
          domain: select

    volume_entity:
      name: "Thực thể: Âm lượng"
      selector:
        entity:
          domain: select

    sound_option:
      name: Chọn Âm thanh
      selector:
        select:
          options:
            - Doorbell
            - Fur Elise
            - Big Ben
            - Ring Ring
            - Lone Ranger
            - Turkish March
            - High Pitched
            - Red Alert
            - Crickets
            - Beep
            - Dog Bark
            - Police Siren
            - Grandfather Clock
            - Phone Ring
            - Fire Truck
            - Clock Chime
            - Alarm Clock
            - School Bell

    volume_option:
      name: Âm lượng
      selector:
        select:
          options:
            - Cao
            - Trung bình
            - Thấp

    duration:
      name: Thời lượng (giây)
      default: 5
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: s

mode: restart

trigger: !input trigger_event

action:
  # 1️⃣ Chọn âm thanh
  - service: select.select_option
    target:
      entity_id: !input sound_entity
    data:
      option: !input sound_option

  # 2️⃣ Chọn âm lượng
  - service: select.select_option
    target:
      entity_id: !input volume_entity
    data:
      option: !input volume_option

  # 3️⃣ Ghi thời lượng vào ESPHome
  - service: number.set_value
    target:
      entity_id: !input duration_number
    data:
      value: !input duration

  # 4️⃣ Kích hoạt còi (ESPHome tự tắt theo thời lượng)
  - service: switch.turn_on
    target:
      entity_id: !input siren_switch
